//WinQLDeviceListModel.cpp

// Copyright Querysoft Limited 2013
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "WinQL/System/Devices/SetupClasses/WinQLDeviceListModel.h"

//--------------------------------------------------------------------------------
namespace nsWin32
{
	using namespace nsWinQAPI;

	//--------------------------------------------------------------------------------
	__QOR_IMPLEMENT_OCLASS_LUID( CDeviceListModel )

	//--------------------------------------------------------------------------------
	CDeviceListModel::CDeviceListModel( CModel* pContainer ) : CPropertySet( pContainer )
	,	m_pGUID			( this, _TXT( "GUID" )			, 0				)
	,	m_szMachine		( this, _TXT( "Machine" )		, 0				)
	,	m_Instances		( this, _TXT( "Instances" )						)
	{
		_WINQ_FCONTEXT( "CDeviceListModel::CDeviceListModel" );
	}

	//--------------------------------------------------------------------------------
	CDeviceListModel::~CDeviceListModel()
	{
		_WINQ_FCONTEXT( "CDeviceListModel::~CDeviceListModel" );
	}

	//--------------------------------------------------------------------------------
	CDeviceListModel::CDeviceListModel( const CDeviceListModel& src ) : CPropertySet( src )
	,	m_pGUID			( this, src.m_pGUID )
	,	m_szMachine		( this, src.m_szMachine )
	,	m_Instances		( this, src.m_Instances )
	{
		_WINQ_FCONTEXT( "CDeviceListModel::CDeviceListModel" );
	}

	//--------------------------------------------------------------------------------
	CDeviceListModel& CDeviceListModel::operator = ( const CDeviceListModel& src )
	{
		_WINQ_FCONTEXT( "CDeviceListModel::operator=" );
		if( &src != this )
		{
			nsMammut::CPropertySet::operator=( src );
			m_pGUID = src.m_pGUID;
			m_szMachine = src.m_szMachine;	
			m_Instances = src.m_Instances;
		}
		return *this;
	}

}//nsWin32

