//WinQLResultOwnerDataImpl.cpp

// Copyright Querysoft Limited 2013, 2015, 2017
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

//Base class implementation for MMC snapin ResultOwnerDataImpl

#include "WinQL/CodeServices/WinQLPolicy.h"
#include "WinQL/Application/Threading/WinQLCriticalSection.h"
#include "WinQL/Application/ErrorSystem/WinQLError.h"
#include "WinQL/COM/Server/MMC/WinQLResultOwnerDataImpl.h"
#include "WinQAPI/OLE32.h"

//--------------------------------------------------------------------------------
namespace nsWin32
{
	using namespace nsWinQAPI;

	__QOR_IMPLEMENT_COMCLASS_ID( CResultOwnerDataImpl, IResultOwnerData );

	//--------------------------------------------------------------------------------
	CResultOwnerDataImpl::CResultOwnerDataImpl( CIUnknownImplBase<>* pImpl ) : CInterfaceImplBase< IResultOwnerData >( pImpl )
	{
		_WINQ_FCONTEXT( "CResultOwnerDataImpl::CResultOwnerDataImpl" );
		RegisterInterface( dynamic_cast< IResultOwnerData* >( this ) );
	}

	//--------------------------------------------------------------------------------
	CResultOwnerDataImpl::~CResultOwnerDataImpl()
	{
		_WINQ_FCONTEXT( "CResultOwnerDataImpl::~CResultOwnerDataImpl" );
	}

	//--------------------------------------------------------------------------------
    long CResultOwnerDataImpl::FindItem( RESULTFINDINFO* pFindInfo, int* pnFoundIndex )
	{
		_WINQ_FCONTEXT( "CResultOwnerDataImpl::FindItem" );
		return E_NOTIMPL;
	}

	//--------------------------------------------------------------------------------
    long CResultOwnerDataImpl::CacheHint( int nStartIndex, int nEndIndex )
	{
		_WINQ_FCONTEXT( "CResultOwnerDataImpl::CacheHint" );
		return E_NOTIMPL;
	}

	//--------------------------------------------------------------------------------
    long CResultOwnerDataImpl::SortItems( int nColumn, unsigned long dwSortOptions, Cmp_long_ptr lUserParam )
	{
		_WINQ_FCONTEXT( "CResultOwnerDataImpl::SortItems" );
		return E_NOTIMPL;
	}

}//nsWin32

