//cpio.h

// Copyright Querysoft Limited 2015
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef	QOR_CPIO_H_3
#define QOR_CPIO_H_3

#include "SystemQOR.h"
#include QOR_SYS_PLATFORMTYPES(cpio)

#	define		C_IRUSR		0000400	//Read by owner
#	define		C_IWUSR		0000200	//Write by owner
#	define		C_IXUSR		0000100	//Execute by owner
#	define		C_IRGRP		0000040	//Read by group
#	define		C_IWGRP		0000020	//Write by group
#	define		C_IXGRP		0000010	//Execute by group
#	define		C_IROTH		0000004	//Read by others
#	define		C_IWOTH		0000002	//Write by others
#	define		C_IXOTH		0000001	//Execute by others
#	define		C_ISUID		0004000	//Set user ID
#	define		C_ISGID		0002000	//Set group ID
#	define		C_ISVTX		0001000	//On directories, restricted deletion flag
#	define		C_ISDIR		0040000	//Directory
#	define		C_ISFIFO	0010000	//FIFO
#	define		C_ISREG		0100000	//Regular file
#	define		C_ISBLK		0060000	//Block special
#	define		C_ISCHR		0020000	//Character special
#	define		C_ISCTG		0110000	//Reserved
#	define		C_ISLNK		0120000	//Symbolic link
#	define		C_ISSOCK	0140000	//Socket

#	define		MAGIC		"070707"

#endif//QOR_CPIO_H_3
