//MammutQOR.cpp

// Copyright Querysoft Limited 2013
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "MammutQOR.h"
#include "CodeQOR/DataTypes/GUID.h"
#include "CodeQOR/Modules/LoadableModuleBase.h"

//------------------------------------------------------------------------------
//Only for shared library builds as one of a network of codependent shared libraries
#ifndef QOR_MONOLITHIC
#	ifdef _USRDLL

__QCMP_STARTLINKAGE_C

	extern int _cdecl QORStaticInit( void );

	//------------------------------------------------------------------------------
	__QCMP_EXPORT int _cdecl QORinit( void )
	{
		QORStaticInit();
		return 1;
	}

	//------------------------------------------------------------------------------
	//This gives the QOR Models library (MammutQOR) a unique identity and marks it as a QOR module
	//with delayed static initialization and an accessible Module Context
	__QCMP_EXPORT nsCodeQOR::mxGUID* QORidentity( void )
	{
		static nsCodeQOR::mxGUID MammutQOR = { 0x6dc84e1d, 0x8faf, 0x4ed2, { 0xbf, 0xe0, 0x8f, 0x44, 0x7, 0x37, 0x33, 0x4a } };
		return &MammutQOR;
	}

__QCMP_ENDLINKAGE_C

	//------------------------------------------------------------------------------
	nsCodeQOR::CLoadableModuleBase& ThisModule( void )
	{
		static nsCodeQOR::CLoadableModuleBase PosumQORModule( "Querysoft Open MVC Model Library (Mammut)" );
		return PosumQORModule;
	}

#	endif//_USRDLL
#endif//QOR_MONOLITHIC
